### ISSUE TITLE
Define and assign common tasks

### ISSUE THREAD

**Issue by jmejia** [turingschool/lesson_plans#166]
What? -  Update the M3 README to include the common day to day tasks that are done during the module and the person responsible for taking care of them.

Example:
Clean fake mustaches: Josh
Bring in Swedish candy: Lovisa
Explain Pokemon: Tess

Why? - Make it easier when rotating or on boarding staff members to know what tasks need to be taken care of. Make it clear to students who they should bring their concern about a specific item to.

**Comment by rwarbelow** [comment]
Tell us more, @jmejia.

**Comment by jmejia** [comment]
@rwarbelow Hahaha I was about to write a description but needed to create new labels so I could tag this and it spiraled into a discussion about whether we should start naming cohorts after Transformers or dinosaurs.
