### ISSUE TITLE
Update links for M3 for README

### ISSUE THREAD

**Issue by jmejia** [turingschool/lesson_plans#169]
Not 100% sure this is a problem, but I want to make sure the links to lesson plans are correct and that the structure for the module accurately reflects the current state. There may be new links to be added as well e.g. Assessment.

**Comment by jmejia** [comment]
There were also Friday sessions that never made it into the repo. One that comes to mind that I'd like to continue doing is "POROs in Rails"

**Comment by applegrain** [comment]
Should the schedule in the README reflect the most recent  iteration of mod3? We didn't do the Friday session that's outlined in week 4 (how-to how-to),  iirc we did the "POROs in Rails" instead.

Also, do you have notes or a lesson plan draft for the "POROs in Rails" class? I couldn't find a related lesson plan.
