### ISSUE TITLE
Update resources links in M3 lesson plans

### ISSUE THREAD

**Issue by jmejia** [turingschool/lesson_plans#170]
Some lesson plans have broken links to resources. I think some of these occurred when we migrated from Dropbox to Drive.

**Comment by tessgriffin** [comment]
I fixed a few resources links. All of the dropbox links in lesson plans still work. I wasn't sure if I should change them to drive links if the dropbox links still work

**Comment by jmejia** [comment]
@tessgriffin Awesome. Thanks! I think it's totally fine to leave them if they work.

**Comment by jmejia** [comment]
@tessgriffin Should we close this?

**Comment by tessgriffin** [comment]
Sure, I'll close it
