### ISSUE TITLE
Update M3 links in README

### ISSUE THREAD

**Issue by jmejia** [turingschool/lesson_plans#178]
There are links to lesson plans that are broken.

**Comment by neight-allen** [comment]
Is this the scope and sequence doc in the lesson-plans repo?

**Comment by jmejia** [comment]
@neight-allen yep :+1:

**Comment by jmejia** [comment]
@neight-allen It's possible that the links broke if someone moved the original lesson plan to the archive. I'm wondering if it makes sense to pull things out of the archive that are active lessons and keep multiple versions of the same lesson (e.g.  consuming_apis_01.md,  consuming_apis_02.md, or  consuming_apis_code_along.md, consuming_apis_tutorial.md). Thoughts?

**Comment by jmejia** [comment]
We'd leave the archive for only lessons that have been removed from the curriculum.
