### ISSUE TITLE
Create POROs in Rails Friday session

### ISSUE THREAD

**Issue by jmejia** [turingschool/lesson_plans#180]
We had a couple lessons that went to the archive on using presenters, decorators, and alternatives to using callbacks at the model level. We probably need an hour and a half for this.

Areas to consider:
- How can we clean up views using presenters?
- What is the decorator pattern and how do we implement it with Ruby?
- When discussing alternatives for callbacks, focus on the problems that callbacks can cause (e.g. after_save can reach into other tables and update data that we can easily forget about leading to unintended consequences.)

**Comment by applegrain** [comment]
See card #172
When completed, update the module 3 Readme with the correct lesson plan link.
