### ISSUE TITLE
Update API curious APIs

### ISSUE THREAD

**Issue by neight-allen** [turingschool/lesson_plans#209]
Instagram has changed their API and it's kind of cumbersome. Tumblr uses an old version of oauth. Let's add some others, like Meetup, Flickr, Twitter, Spotify, Strava

**Comment by neight-allen** [comment]
Looking for APIs that have lots of public data, a working oAuth gem, good documentation, and simple authentication for HTTP requests. Twitter is bad because it requires you to sign all of your requests (which is complicated) and Spotify has expiring oAuth tokens, which just adds complexity.

**Comment by neight-allen** [comment]
Just do by the end of this inning. We won't revisit this until the next.

**Comment by martensonbj** [comment]
Vine - (6 second video app) - https://github.com/starlock/vino/wiki/API-Reference
Pinterest - https://developers.pinterest.com/docs/api/overview/
Stripe - https://stripe.com/docs/api/ruby#idempotent_requests

**Comment by neight-allen** [comment]
There's a big list in the self directed project lesson. I've heard pinterest also locks people in a sandbox, and I'm not sure what info there would be to consume on Stripe. There wont be any transactions.

**Comment by neight-allen** [comment]
Added foursquare and reddit
